[variables]
PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "tesseract",
  "poppler_utils",
  "imagemagick",
  "file"
]

[phases.install]
cmds = [
  "python3.11 -m pip install --upgrade pip",
  "python3.11 -m pip install -r requirements.txt"
]

[start]
cmd = "python3.11 -m uvicorn main:app --host 0.0.0.0 --port $PORT"
