[phases.setup]
nixPkgs = [
  "python311",
  "tesseract",
  "poppler_utils", 
  "gcc",
  "pkg-config",
  "libffi",
  "openssl",
  "postgresql"
]

[phases.install]
cmds = [
  "pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
